/// The contract between `fern/` and the app.
///
/// The Rive file is generated by a Python script and built by a CLI that is not
/// part of the Flutter toolchain, so nothing in `flutter analyze` or the rest of
/// the suite would notice if a rename broke it. Names are the whole interface —
/// `fern/NOTES.md` calls them "the public surface" — and every one of them fails
/// *silently* at runtime: a missing artboard throws, but a renamed view model
/// property just leaves the plant sitting at its authored pose forever.
///
/// Requires the native library. If this fails with "Failed to open dynamic
/// library", run:
///
///     dart run rive_native:setup --platform macos
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:rive/rive.dart';

const String fernAsset = 'assets/rive/fern.riv';

/// Every growth stage the engine can report, and the artboard that draws it.
///
/// `Stage.seed` is deliberately absent — the fern has no seed artboard yet, and
/// the garden has to decide what a just-planted habit looks like.
const Map<String, String> stageArtboards = {
  'sprout': 'FernSprout',
  'seedling': 'FernSeedling',
  'young': 'FernYoung',
  'mature': 'FernMature',
  'bloom': 'FernBloom',
};

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late File file;

  setUpAll(() async {
    expect(
      await RiveNative.init(),
      isTrue,
      reason: 'RiveNative.init() failed — run `dart run rive_native:setup`',
    );
    // Factory.flutter, not Factory.rive: the Rive renderer needs a graphics
    // context, and asserts in native code under `flutter test`.
    final loaded = await File.asset(fernAsset, riveFactory: Factory.flutter);
    expect(loaded, isNotNull, reason: '$fernAsset did not decode');
    file = loaded!;
  });

  for (final entry in stageArtboards.entries) {
    test('${entry.value} exposes the state machine and vitality', () {
      final controller = RiveWidgetController(
        file,
        artboardSelector: ArtboardNamed(entry.value),
        stateMachineSelector: const StateMachineNamed('Fern'),
      );
      addTearDown(controller.dispose);

      final vitality = controller.dataBind(DataBind.auto()).number('vitality');
      expect(
        vitality,
        isNotNull,
        reason: '${entry.value} has no `vitality` number on its view model',
      );

      // Writable, and reads back — a bind that resolved but drives nothing
      // would still pass this, which is why fern/ verifies the rendering side.
      vitality!.value = 0.25;
      expect(vitality.value, closeTo(0.25, 1e-9));
    });
  }

  test('an unknown artboard throws rather than falling back', () {
    // The Rive CLI silently renders the default artboard for an unknown name.
    // The runtime does not, so a typo here is a loud failure, not a wrong plant.
    expect(
      () => RiveWidgetController(
        file,
        artboardSelector: const ArtboardNamed('FernNope'),
      ),
      throwsA(isA<RiveArtboardException>()),
    );
  });
}
