/// The contract between `fern/` and the app.
///
/// The Rive file is generated by a Python script and built by a CLI that is not
/// part of the Flutter toolchain, so nothing in `flutter analyze` or the rest of
/// the suite would notice if a rename broke it. Names are the whole interface —
/// `fern/NOTES.md` calls them "the public surface" — and every one of them fails
/// *silently* at runtime: a missing artboard throws, but a renamed view model
/// property just leaves the plant sitting at its authored pose forever.
///
/// Requires the native library. If this fails with "Failed to open dynamic
/// library", run:
///
///     dart run rive_native:setup --platform macos
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:rive/rive.dart';

import 'package:taproot/core/engine/domain.dart';
import 'package:taproot/features/garden/domain/plant_art.dart';

// Named from the app's constants, so the test cannot pass against a path or
// a name the app no longer uses.
const String fernAsset = fernAssetPath;

/// Every growth stage the engine can report, and the artboard that draws it.
///
/// One entry per [Stage] value, and the map is the checklist: an artboard that
/// is not in here is not checked, so a stage added to `fern/` without a line
/// here ships unverified.
///
/// `FernSeed` is the odd one. It carries the same state machine and the same
/// `vitality` binding as the rest, so every assertion below holds — but it is
/// deliberately inert to vitality, because the engine has none before the first
/// completion. It sways; it does not droop. Do not extend these tests with
/// "writing vitality changes the render" without exempting it.
///
/// Not every artboard is a stage: `fern/` also has [fernRootsArtboard], which draws
/// below the ground line and is composed separately.
final Map<String, String> stageArtboards = {
  for (final stage in Stage.values) stage.name: fernArtboardFor(stage),
};

/// The two numbers the garden writes, named from the app's own constants rather
/// than retyped — a test that spells them itself would still pass after a
/// rename that broke the app.
const List<String> fernNumbers = [fernVitalityProperty, fernRootsProperty];

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late File file;

  setUpAll(() async {
    expect(
      await RiveNative.init(),
      isTrue,
      reason: 'RiveNative.init() failed — run `dart run rive_native:setup`',
    );
    // Factory.flutter, not Factory.rive: the Rive renderer needs a graphics
    // context, and asserts in native code under `flutter test`.
    final loaded = await File.asset(fernAsset, riveFactory: Factory.flutter);
    expect(loaded, isNotNull, reason: '$fernAsset did not decode');
    file = loaded!;
  });

  for (final name in [...stageArtboards.values, fernRootsArtboard]) {
    test('$name exposes the state machine and both numbers', () {
      final controller = RiveWidgetController(
        file,
        artboardSelector: ArtboardNamed(name),
        stateMachineSelector: const StateMachineNamed(fernStateMachineName),
      );
      addTearDown(controller.dispose);
      final instance = controller.dataBind(DataBind.auto());

      for (final property in fernNumbers) {
        final number = instance.number(property);
        expect(
          number,
          isNotNull,
          reason: '\$name has no `\$property` number on its view model',
        );

        // Writable, and reads back — a bind that resolved but drives nothing
        // would still pass this, which is why fern/ verifies the rendering
        // side. `roots` in particular drives the root system on one artboard
        // and a lean on another, and neither is visible from here.
        number!.value = 0.25;
        expect(number.value, closeTo(0.25, 1e-9));
      }
    });
  }

  test('one view model instance drives a stage and its roots together', () {
    // The composition the garden needs: `FernRoots` stacked under a stage
    // artboard, both reading the same `roots`. It has to be one *instance* —
    // `roots` drives the root system on one artboard and a lean on the other,
    // so two instances would let the plant lean one way while the roots it is
    // leaning about say something else.
    //
    // Nesting the roots artboard inside the plant is the obvious alternative
    // and does not work: a bind inside a NestedArtboard resolves to nothing,
    // silently, with a clean verify. Hence stacking two artboards in Flutter.
    final viewModel = file.defaultArtboardViewModel(
      file.artboard('FernMature')!,
    );
    final shared = viewModel!.createDefaultInstance();
    expect(shared, isNotNull);

    final plant = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed('FernMature'),
      stateMachineSelector: const StateMachineNamed('Fern'),
    );
    final roots = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed(fernRootsArtboard),
      stateMachineSelector: const StateMachineNamed('Fern'),
    );
    addTearDown(plant.dispose);
    addTearDown(roots.dispose);

    final boundToPlant = plant.dataBind(DataBind.byInstance(shared!));
    final boundToRoots = roots.dataBind(DataBind.byInstance(shared));

    // One write, seen by both. This is the whole assertion.
    shared.number(fernRootsProperty)!.value = 0.5;
    expect(boundToPlant.number(fernRootsProperty)!.value, closeTo(0.5, 1e-9));
    expect(boundToRoots.number(fernRootsProperty)!.value, closeTo(0.5, 1e-9));

    // And both artboards accept being advanced against it. `fern/` eases this
    // value over 1.2s, so the poses are reached by elapsed time rather than by
    // the write — advancing is what makes it arrive.
    expect(plant.stateMachine.advanceAndApply(1.5), isA<bool>());
    expect(roots.stateMachine.advanceAndApply(1.5), isA<bool>());
  });

  test('two auto-binds do not share a value', () {
    // The failure mode the test above exists to prevent, pinned so it is
    // obvious why `DataBind.auto()` is wrong for the stacked pair. Auto-binding
    // is right for a lone plant and wrong the moment roots are under it.
    final plant = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed('FernMature'),
      stateMachineSelector: const StateMachineNamed('Fern'),
    );
    final roots = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed(fernRootsArtboard),
      stateMachineSelector: const StateMachineNamed('Fern'),
    );
    addTearDown(plant.dispose);
    addTearDown(roots.dispose);

    plant.dataBind(DataBind.auto()).number(fernRootsProperty)!.value = 0.75;
    expect(
      roots.dataBind(DataBind.auto()).number(fernRootsProperty)!.value,
      isNot(closeTo(0.75, 1e-9)),
      reason: 'auto-bound instances are meant to be independent',
    );
  });

  test('an unknown artboard throws rather than falling back', () {
    // The Rive CLI silently renders the default artboard for an unknown name.
    // The runtime does not, so a typo here is a loud failure, not a wrong plant.
    expect(
      () => RiveWidgetController(
        file,
        artboardSelector: const ArtboardNamed('FernNope'),
      ),
      throwsA(isA<RiveArtboardException>()),
    );
  });
}
