/// The contract between `oak/` and the app.
///
/// The same contract `fern_asset_test.dart` pins, for the second species. The
/// `.riv` is generated by a Python script and built by a CLI outside the Flutter
/// toolchain, so nothing else in the suite would notice a rename — and every one
/// of these names fails *silently* at runtime, leaving a plant at its authored
/// pose forever rather than throwing.
///
/// **Deliberately self-contained.** It spells the oak's names itself instead of
/// importing them, because `plant_art.dart` is fern-only today
/// (`fernPlantType`, `fernStateMachineName`, `hasPlantArt`) and the oak has no
/// constants there to import. That is the one thing `fern_asset_test.dart` is
/// careful *not* to do, so treat it as temporary: when `plant_art.dart` learns a
/// species → (artboard prefix, state machine, view model) map, these two files
/// should collapse into one test parameterised over it, reading the names from
/// the app the way the fern's does.
///
/// Requires the native library. If this fails with "Failed to open dynamic
/// library", run:
///
///     dart run rive_native:setup --platform macos
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:rive/rive.dart';

import 'package:taproot/core/engine/domain.dart';

const String oakAsset = 'assets/rive/oak.riv';
const String oakStateMachineName = 'Oak';
const String oakVitalityProperty = 'vitality';
const String oakRootsProperty = 'roots';
const String oakRootsArtboard = 'OakRoots';

/// One entry per [Stage]: the map is the checklist, so a stage added to `oak/`
/// without a line here ships unverified.
///
/// `OakSeed` is the odd one, exactly as `FernSeed` is. It carries the same state
/// machine and the same `vitality` binding, so every assertion below holds — but
/// it is deliberately inert to vitality, because the engine has none before the
/// first completion. Measured in `oak/`: 0 px change between vitality 1 and 0,
/// and 418 px across sway frames. It sways; it does not droop. Do not extend
/// these tests with "writing vitality changes the render" without exempting it.
String oakArtboardFor(Stage stage) => switch (stage) {
  Stage.seed => 'OakSeed',
  Stage.sprout => 'OakSprout',
  Stage.seedling => 'OakSeedling',
  Stage.young => 'OakYoung',
  Stage.mature => 'OakMature',
  Stage.bloom => 'OakBloom',
};

final List<String> oakStageArtboards = [
  for (final stage in Stage.values) oakArtboardFor(stage),
];

const List<String> oakNumbers = [oakVitalityProperty, oakRootsProperty];

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late File file;

  setUpAll(() async {
    expect(
      await RiveNative.init(),
      isTrue,
      reason: 'RiveNative.init() failed — run `dart run rive_native:setup`',
    );
    // Factory.flutter, not Factory.rive: the Rive renderer needs a graphics
    // context, and asserts in native code under `flutter test`.
    final loaded = await File.asset(oakAsset, riveFactory: Factory.flutter);
    expect(loaded, isNotNull, reason: '$oakAsset did not decode');
    file = loaded!;
  });

  for (final name in [...oakStageArtboards, oakRootsArtboard]) {
    test('$name exposes the state machine and both numbers', () {
      final controller = RiveWidgetController(
        file,
        artboardSelector: ArtboardNamed(name),
        stateMachineSelector: const StateMachineNamed(oakStateMachineName),
      );
      addTearDown(controller.dispose);
      final instance = controller.dataBind(DataBind.auto());

      for (final property in oakNumbers) {
        final number = instance.number(property);
        expect(
          number,
          isNotNull,
          reason: '$name has no `$property` number on its view model',
        );

        // Writable, and reads back. A bind that resolved but drives nothing
        // would still pass this, which is why `oak/` proves the rendering side
        // separately — 21 A/B renders, recorded in oak/NOTES.md step 2.
        number!.value = 0.25;
        expect(number.value, closeTo(0.25, 1e-9));
      }
    });
  }

  test('one view model instance drives a stage and its roots together', () {
    // The composition the garden needs, identical to the fern's: `OakRoots`
    // stacked under a stage artboard, both reading one shared `roots`. It has
    // to be one *instance* — `roots` drives the root system on one artboard and
    // the stability lean on the other, so two instances would let the tree lean
    // as though it were shallow while the roots below it were deep.
    //
    // Nesting the roots inside the plant is the obvious alternative and does
    // not work: a bind inside a NestedArtboard resolves to nothing, silently,
    // with a clean verify. Hence stacking two artboards in Flutter.
    final viewModel = file.defaultArtboardViewModel(
      file.artboard('OakMature')!,
    );
    final shared = viewModel!.createDefaultInstance();
    expect(shared, isNotNull);

    final plant = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed('OakMature'),
      stateMachineSelector: const StateMachineNamed(oakStateMachineName),
    );
    final roots = RiveWidgetController(
      file,
      artboardSelector: const ArtboardNamed(oakRootsArtboard),
      stateMachineSelector: const StateMachineNamed(oakStateMachineName),
    );
    addTearDown(plant.dispose);
    addTearDown(roots.dispose);

    final boundToPlant = plant.dataBind(DataBind.byInstance(shared!));
    final boundToRoots = roots.dataBind(DataBind.byInstance(shared));

    // One write, seen by both. This is the whole assertion.
    shared.number(oakRootsProperty)!.value = 0.5;
    expect(boundToPlant.number(oakRootsProperty)!.value, closeTo(0.5, 1e-9));
    expect(boundToRoots.number(oakRootsProperty)!.value, closeTo(0.5, 1e-9));

    // And both accept being advanced against it. `oak/` eases this value, so
    // the poses are reached by elapsed time rather than by the write —
    // advancing is what makes it arrive.
    expect(plant.stateMachine.advanceAndApply(1.5), isA<bool>());
    expect(roots.stateMachine.advanceAndApply(1.5), isA<bool>());
  });

  test('the oak stacks on the same ground line as the fern', () async {
    // `GardenLayout.rootsDepth` is a single global constant, not per-species.
    // That is only correct while every species' roots artboard is the same
    // size, so pin it here rather than discovering it as a misaligned ground
    // line the day the garden learns to draw a second plant.
    final fern = await File.asset(
      'assets/rive/fern.riv',
      riveFactory: Factory.flutter,
    );
    expect(fern, isNotNull, reason: 'assets/rive/fern.riv did not decode');

    final oakRoots = file.artboard(oakRootsArtboard)!;
    final fernRoots = fern!.artboard('FernRoots')!;

    expect(oakRoots.width, closeTo(fernRoots.width, 1e-6));
    expect(oakRoots.height, closeTo(fernRoots.height, 1e-6));
  });

  test('an unknown artboard throws rather than falling back', () {
    // The Rive CLI silently renders the default artboard for an unknown name —
    // one of the "three ways to preview nothing" in fern/NOTES.md. The runtime
    // does not, so a typo here is a loud failure rather than the wrong plant.
    expect(
      () => RiveWidgetController(
        file,
        artboardSelector: const ArtboardNamed('OakNope'),
      ),
      throwsA(isA<RiveArtboardException>()),
    );
  });
}
