/// The contract between the generator projects (`fern/`, `oak/`, `plantgen/`)
/// and the app, for **every** species at once.
///
/// Each `.riv` is generated by a Python script and built by a CLI that is not
/// part of the Flutter toolchain, so nothing in `flutter analyze` or the rest of
/// the suite would notice a rename. Names are the whole interface — `fern/`'s
/// notes call them "the public surface" — and every one of them fails
/// *silently* at runtime: a missing artboard throws, but a renamed view model
/// property just leaves the plant sitting at its authored pose forever.
///
/// **Parameterised over `plantArts`, and it spells nothing itself.** Every name
/// here comes from the [PlantArt] the app uses, so a rename cannot pass by
/// being made consistently in two places — and a species added to `plantArts`
/// is covered the moment it is added, with no line to remember here. That is
/// the one property the two per-species tests this replaces could not have.
///
/// Requires the native library. If this fails with "Failed to open dynamic
/// library", run:
///
///     dart run rive_native:setup --platform macos
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:rive/rive.dart';

import 'package:taproot/core/engine/domain.dart';
import 'package:taproot/features/garden/domain/plant_art.dart';
import 'package:taproot/features/habits/domain/plant_choices.dart';

/// The two numbers the garden writes, named from the app's own constants rather
/// than retyped — a test that spelled them itself would still pass after a
/// rename that broke the app.
const List<String> plantNumbers = [plantVitalityProperty, plantRootsProperty];

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUpAll(() async {
    expect(
      await RiveNative.init(),
      isTrue,
      reason: 'RiveNative.init() failed — run `dart run rive_native:setup`',
    );
  });

  /// Decoded once per species and shared by that species' group.
  final files = <String, File>{};

  Future<File> fileFor(PlantArt art) async {
    final cached = files[art.plantType];
    if (cached != null) return cached;
    // Factory.flutter, not Factory.rive: the Rive renderer needs a graphics
    // context, and asserts in native code under `flutter test`.
    final loaded = await File.asset(
      art.assetPath,
      riveFactory: Factory.flutter,
    );
    expect(loaded, isNotNull, reason: '${art.assetPath} did not decode');
    return files[art.plantType] = loaded!;
  }

  test('every species with art is a plant the user can actually choose', () {
    // `Habit.plantType` is free-form, so nothing else would catch art keyed to
    // an id the creation flow never offers — it would simply never draw.
    for (final art in plantArts) {
      expect(
        plantChoiceById(art.plantType),
        isNotNull,
        reason:
            '${art.plantType} has art but is not in plantChoices, '
            'so no habit can ever be created that draws it',
      );
    }
  });

  for (final art in plantArts) {
    group(art.plantType, () {
      /// One entry per [Stage], plus the roots. The loop over `Stage.values` is
      /// the checklist: a stage added to the engine is covered here
      /// automatically, and `PlantArt.artboardFor` is a compile-time-exhaustive
      /// switch, so it cannot quietly go missing either.
      final artboards = <String>[
        for (final stage in Stage.values) art.artboardFor(stage),
        art.rootsArtboard,
      ];

      for (final name in artboards) {
        test('$name exposes the state machine and both numbers', () async {
          final file = await fileFor(art);
          final controller = RiveWidgetController(
            file,
            artboardSelector: ArtboardNamed(name),
            stateMachineSelector: StateMachineNamed(art.stateMachineName),
          );
          addTearDown(controller.dispose);
          final instance = controller.dataBind(DataBind.auto());

          for (final property in plantNumbers) {
            final number = instance.number(property);
            expect(
              number,
              isNotNull,
              reason: '$name has no `$property` number on its view model',
            );

            // Writable, and reads back — a bind that resolved but drives
            // nothing would still pass this, which is why each generator
            // project proves the rendering side itself (`check_render.py`).
            number!.value = 0.25;
            expect(number.value, closeTo(0.25, 1e-9));
          }
        });
      }

      test(
        'one view model instance drives a stage and its roots together',
        () async {
          // The composition the garden needs: the roots artboard stacked under a
          // stage artboard, both reading the same `roots`. It has to be one
          // *instance* — `roots` drives the root system on one artboard and a
          // lean on the other, so two instances would let the plant lean as
          // though it were shallow while the roots drawn below it were deep.
          //
          // Nesting the roots inside the plant is the obvious alternative and
          // does not work: a bind inside a NestedArtboard resolves to nothing,
          // silently, with a clean verify. Hence stacking two artboards.
          final file = await fileFor(art);
          final mature = art.artboardFor(Stage.mature);
          final viewModel = file.defaultArtboardViewModel(
            file.artboard(mature)!,
          );
          final shared = viewModel!.createDefaultInstance();
          expect(shared, isNotNull);

          final plant = RiveWidgetController(
            file,
            artboardSelector: ArtboardNamed(mature),
            stateMachineSelector: StateMachineNamed(art.stateMachineName),
          );
          final roots = RiveWidgetController(
            file,
            artboardSelector: ArtboardNamed(art.rootsArtboard),
            stateMachineSelector: StateMachineNamed(art.stateMachineName),
          );
          addTearDown(plant.dispose);
          addTearDown(roots.dispose);

          final boundToPlant = plant.dataBind(DataBind.byInstance(shared!));
          final boundToRoots = roots.dataBind(DataBind.byInstance(shared));

          // One write, seen by both. This is the whole assertion.
          shared.number(plantRootsProperty)!.value = 0.5;
          expect(
            boundToPlant.number(plantRootsProperty)!.value,
            closeTo(0.5, 1e-9),
          );
          expect(
            boundToRoots.number(plantRootsProperty)!.value,
            closeTo(0.5, 1e-9),
          );

          // And both artboards accept being advanced against it. The generator
          // eases this value over 1.2s, so the poses are reached by elapsed time
          // rather than by the write — advancing is what makes it arrive.
          expect(plant.stateMachine.advanceAndApply(1.5), isA<bool>());
          expect(roots.stateMachine.advanceAndApply(1.5), isA<bool>());
        },
      );

      test('two auto-binds do not share a value', () async {
        // The failure mode the test above exists to prevent, pinned so it is
        // obvious why `DataBind.auto()` is wrong for the stacked pair.
        // Auto-binding is right for a lone plant and wrong the moment roots are
        // under it.
        final file = await fileFor(art);
        final plant = RiveWidgetController(
          file,
          artboardSelector: ArtboardNamed(art.artboardFor(Stage.mature)),
          stateMachineSelector: StateMachineNamed(art.stateMachineName),
        );
        final roots = RiveWidgetController(
          file,
          artboardSelector: ArtboardNamed(art.rootsArtboard),
          stateMachineSelector: StateMachineNamed(art.stateMachineName),
        );
        addTearDown(plant.dispose);
        addTearDown(roots.dispose);

        plant.dataBind(DataBind.auto()).number(plantRootsProperty)!.value =
            0.75;
        expect(
          roots.dataBind(DataBind.auto()).number(plantRootsProperty)!.value,
          isNot(closeTo(0.75, 1e-9)),
          reason: 'auto-bound instances are meant to be independent',
        );
      });

      test('an unknown artboard throws rather than falling back', () async {
        // The Rive CLI silently renders the *default* artboard for an unknown
        // name — one of the "three ways to preview nothing" in fern/NOTES.md.
        // The runtime does not, so a typo is a loud failure rather than the
        // wrong plant quietly drawn.
        final file = await fileFor(art);
        expect(
          () => RiveWidgetController(
            file,
            artboardSelector: ArtboardNamed('${art.name}Nope'),
          ),
          throwsA(isA<RiveArtboardException>()),
        );
      });
    });
  }

  test('every species stacks on the same ground line', () async {
    // `GardenLayout.rootsDepth` is a single global constant, not per-species.
    // That is only correct while every species' roots artboard is the same
    // size, so pin it here rather than discovering it as a misaligned ground
    // line the day a third species ships.
    //
    // If this fails, the fix is to make rootsDepth per-species — not to resize
    // the artboard, which would change art someone has reviewed.
    ({double width, double height})? first;
    String? firstSpecies;
    for (final art in plantArts) {
      final file = await fileFor(art);
      final roots = file.artboard(art.rootsArtboard)!;
      final size = (width: roots.width, height: roots.height);
      if (first == null) {
        first = size;
        firstSpecies = art.plantType;
        continue;
      }
      expect(
        size,
        first,
        reason:
            '${art.plantType} roots are $size but $firstSpecies roots are '
            '$first; GardenLayout.rootsDepth assumes one size for all species',
      );
    }
  });
}
